version: '3.8'

services:
  backend:
    build: .
    container_name: lorawan-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - MQTT_URL=mqtt://mosquitto:1883
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    networks:
      - chirpstack-docker_default

networks:
  chirpstack-docker_default:
    external: true
